name: Release And Publish

on:
  push:
    tags: ["v*"]
  workflow_dispatch:
    inputs:
      version:
        # This input isn't actually used as an input, but it's a reminder that
        # this workflow can only automatically push patch versions.
        # This is because often minor versions require human intervention, so
        # it's safer if we force ourselves to always create them locally.
        description: ⚠️ This workflow can only automatically release patch versions
        required: true
        default: patch

jobs:
  build:
    runs-on: ubuntu-latest
    needs: git-version
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn
      - run: yarn test

  git-version:
    name: Create git tag and commit
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    outputs:
      branch: ${{ steps.push.outputs.branch }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set Owner as committer
        run: |
          git config user.name "pascallin"
          git config user.email "pascal_lin@foxmail.com"
      - name: Create new version
        run: |
          yarn lerna version --yes patch

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: yarn lerna publish --yes --from-package
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
